language: node_js
node_js: stable
cache: npm
script: npm run build && npm test
deploy:
  - provider: npm
    skip_cleanup: true
    email: parkjs814@gmail.com
    api_key:
      secure: P4VWqDnW3WEhY3j5wQ3C/etGXHPuMfoeKaqhLgdpBpKr5YrhmrTFdPZ0k6hYUSdD9jwlus2BzxPAgmocuEU6K83NLAr6ziivhNp+rDs8U8YLQi38iyZCF5TFXG8B74YZpofPz1s3GgRBNahJ7fxJ9alWpwkocahwCOAIbL2nUgAgspSdO9syLSEX471wYRIWu0ivmF6wukVbHYu8s3Kc2VSYF8VUzG6k+L9pmtXjVb8RDr2wAxH1yx92sQMCyiqSwlVoS6RqdU8LpZvFE4Iw6NvJ0v+5I3fsrf5X8i/VcQrTP6Bj23Q0w9QOPa20cDgdxk22knK61xPC3o7CV5lGtTNUP8Tpqelstrexk6m2St/UxqtlyDuviUNhy39rGqVc6tebMNjZWXekg3jiZ06xVMWHUTfBl1nnrLMUbM4tgTHQvXtHT7GOozCpypafiWrif+jDtiXOayea2N1k2n8OlvxGLbiE934ReZsfkv04RbLVs+gJj3cRkr5t0JoDNxhHTkTELEfb/7PLAHJJ2XhuUtzGoDn8B+8Zz+9ZRCaIgpAoNa19MAiPV/lqqK+W8+i3p1GTn7raUbp6S2JIP3L257psv/NSMQzmrB26EVx0j0fjjOUTE1JXLBT1Gfu1ntGocE24ePnbtl26iUzBP5hiW+zchGCk2YVjz0NuUTOzm0A=
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: na9rnofudeHOVxEvhoN9BLI03Zx629XxlEDx22X43aJM4C1pqBG7/V+Cfs6KzYxKR2oarY/BIi+EWi73HpDikz+MKgvffz4UamMreJp6byxByILI9kF6dvWybZUW5OvW1JVsRPpzyOXmcXrIKvHdq/z+s+9ljEXWHhu0wWt7/gFVD2LYhSDfjOruT1zbPjDb59YD83N2itQdYiujvMNO2BXehyOpjAVXofgMu70ZVKDlI1Qi3PdFCZFhAMKsHCOOq5/ib6tWxZ/JGNsYIl/p4pEgozvYDbuLHkmk7y05gq56PAaTW1/hf7lKwCNGTzMpQ0/iIK+grb+vTrqKUQibqddF9zyUsYeKWdNse2WsqCgwYxmLGNjOiRumxn1EwKRFaqnsE0nyK46vCaM64wVozQ84mGfhnoXxAwOTc9vmK0ga9h0hw0uGOQdW6Hsa6Ab+LWs11im0FIVp95XdRikhBYP8w0ZMDdv+o21eFvm7lXyhLS3A4lS2xRG/HgkU+/fcevY2zuclp1iFm2QzH3anp88+mr8m3qYGa8WYqnP5b7j0ifXTvxGDw1Q7BBslcP0NP0M5BjxpR6aVa2kI/R5jK9k6x3XxFtio3eFMxTKcgdL2tMIF2uYLVPP+CUuvPQk3H4T+iio7aeiWaJRiiLxX5PL+B0R6ICe5cAraGo2zw0g=
    on:
      branch: master
      tags: true
  - provider: script
    script: npm run docs && gh-pages -d docs
    on:
      branch: master
      tags: true
