language: node_js
node_js: stable
cache: npm
script: npm run build && npm test && npm run docs
deploy:
  - provider: npm
    skip_cleanup: true
    email: parkjs814@gmail.com
    api_key: $NPM_ACCESS_TOKEN
    on:
      branch: master
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    local_dir: docs
    keep_history: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    on:
      branch: master
      tags: true
env:
  global:
    # NPM_ACCESS_TOKEN
    - secure: VHe079bX5VMS5oESykR+2z7hDUt8i8FyikzGGEb5JauXkf9HjOuje8MmYmLEtfYQ9Q/3ek3dlCUEGU/3GpZLSaRGVfpo/Is3g4ZS3INVe3M2JSqSm22AptFO72cGpzgiflDHcaD+P5mXGsJAwO4AzThUsQl+AtbEUPeiNG0fz4PEKKYMld7B+vAVTtQ33Si5k6rSMdyWr/FYC8i97My7hOC5YY19JRgNn7iXJ7HR/FPsclzVpG+uSLpFbMhVLlgnPR23O5+AiI3D3sXwHgZU59uFsLpJQ2u7+WxMPX3exi0fFkAqXg+t92PcVsEH9SAFqOYyE2DkhP1blVnLt3D78jTlCZ74CY0s/L2B+xFm8xN4g5K/BHRDeOZXnjo+tuSp/iX5gX4WxzkLK5Qt2+1pjevUwHCo2m0ZIpcoQdvjS9B0s+8y7TolIjmjCRe9htxVqsjRxySLXMD6HAmQ90suvH0ciZU1GAW+SVKwrad8795UCdGG6oAiJcFK9O88gbr570jfpGFe96RkNkq+QZr1BSmL6FxDVdwJBD7T4taYKajhy9TCNcLKjL7w/UKf2TnrJ6Fq+3kKEHaLwfxv38+3hWT/oQEWS3A2QpO6Gx1DOVHY/6AGwUsw0R11v70JYkeHx/AB4TYZ8NLeF2bCH02a5e6xZOWetjUhNj08mFpN48c=
    # GITHUB_ACCESS_TOKEN
    - secure: L3rPgzynYqyc4LudtvJYBu7IRR5rlsjDAy54vcWaMWTM6oY7XlBKqWQLzS1H6tlvSTN0J5x2fC2xMUQUuqYgY0jAkx3hOrMoT6uIn2Qk08i5B6H7wwiwe3yZ6tQd9KlFy1KAU9TwZChAk30M2Tj8MMwQJWzNCKC01gRjD2PF7rDDKsC9HeZpV+53M12CVxJMfEuBJAkT1D1eZ5jZM3BcgNkAKtoOfb99XpE/zycHckDs7RoDAfaUbHpbUi2T+J2M4Y926y8YkFLkjskqYIj+E8J9btqwEStl1clgECO0IZj0NtLLwLQ91mtAB4973djzX2kJkF8Qy1Q6c5r8knM0WPSIwYIOAPcptquwTVFW7p4rVeXRHNUMRW//rOjMhqC/mlWvjf+CyE2zggWfJ2ONV2V5m6w7B87fv1W9UmdfO1TRM9S4SSsFMfLodw65Q0Uw9cIkla/AKrdVkEbeM2j0uk3IDFgUV+a1Jc2n8kL0pL5hdRlSFwbKN/5kM1aF/6tUIPEkboUg3X7aZ2n2cDm5c4hqutEAC60NmG5BJdim5Dg5t7kVmZTKdxwx/za4jgSzwpSBoUnE9ErBikicy0l0OCYaiNRHpyKPk7l+K54O9Pyl+d+mWKyfQx8PFQrG0LYAFtPh17Lff7K2n+Dope4mZSyvidsei6muskebLZfIeKc=
